/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function createBlockJson(id: string, content: string): string
export declare function generateCandidateJson(loreJson: string, configJson: string): string
export declare function renderLoreSummaryJson(loreJson: string): string
export declare function schemaBundleJson(): string
export declare function version(): string
