/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseUri(uriStr: string): string
export declare function parseManifest(yamlStr: string): string
export declare function resolve(uriStr: string, repoBasePath: string): string
export declare function version(): string
