/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseUri(uriStr: string): string
export declare function uriNew(repository: string, entityType: string, entityId: string, fragment?: string | undefined | null): string
export declare function uriIdentity(uriStr: string): string
export declare function uriManifestPath(uriStr: string): string
export declare function uriFormat(repository: string, entityType: string, entityId: string, fragment?: string | undefined | null): string
export declare function entityTypeParse(s: string): string
export declare function entityTypeDirectoryName(entityType: string): string
export declare function entityTypeList(basePath: string, repository: string): string
export declare function parseManifest(yamlStr: string): string
export declare function manifestNew(repository: string, entityType: string, entityId: string, name: string): string
export declare function manifestToYaml(jsonStr: string): string
export declare function manifestFromYaml(yamlStr: string): string
export declare function manifestContentHash(jsonStr: string): string
export declare function manifestSetProperty(jsonStr: string, key: string, value: string): string
export declare function manifestAddReference(jsonStr: string, key: string, value: string): string
export declare function manifestSetRepresentation(jsonStr: string, key: string, hash: string, format: string, uri?: string | undefined | null, tier?: string | undefined | null): string
export declare function manifestBumpVersion(jsonStr: string): string
export declare function contentHashFromBytes(data: Buffer): string
export declare function contentHashFromString(s: string): string
export declare function contentHashParse(s: string): string
export declare function contentHashVerify(hashStr: string, data: Buffer): boolean
export declare function contentHashHexDigest(hashStr: string): string
export declare function changeSet(path: string, oldValue: string | undefined | null, newValue: string): string
export declare function changeDelete(path: string, oldValue: string): string
export declare function changeAppend(path: string, newValue: string): string
export declare function commitNew(parent: string | undefined | null, author: string, message: string, manifestHash: string, changesJson: string): string
export declare function commitVerifyId(jsonStr: string): boolean
export declare function repoInit(basePath: string, repository: string): string
export declare function repoOpen(basePath: string, repository: string): string
export declare function repoCreateEntity(basePath: string, repository: string, entityType: string, entityId: string, name: string, author: string): string
export declare function repoReadManifest(basePath: string, repository: string, entityType: string, entityId: string): string
export declare function repoReadManifestAtRef(basePath: string, repository: string, entityType: string, entityId: string, reference: string): string
export declare function repoWriteManifest(basePath: string, repository: string, manifestJson: string): string
export declare function repoCommitManifest(basePath: string, repository: string, entityType: string, entityId: string, message: string, author: string, changesJson: string): string
export declare function repoDeleteEntity(basePath: string, repository: string, entityType: string, entityId: string, author: string): string
export declare function repoHistory(basePath: string, repository: string, entityType: string, entityId: string, limit: number): string
export declare function repoListEntities(basePath: string, repository: string, entityType: string): string
export declare function repoCreateBranch(basePath: string, repository: string, name: string): string
export declare function repoSwitchBranch(basePath: string, repository: string, name: string): string
export declare function repoListBranches(basePath: string, repository: string): string
export declare function repoHeadHash(basePath: string, repository: string): string
export declare function repoRevertCommit(basePath: string, repository: string, commitHash: string, author: string): string
export declare function repoAddRemote(basePath: string, repository: string, name: string, url: string): string
export declare function repoRemoveRemote(basePath: string, repository: string, name: string): string
export declare function repoListRemotes(basePath: string, repository: string): string
export declare function repoPush(basePath: string, repository: string, remote?: string | undefined | null, branch?: string | undefined | null): string
export declare function repoPull(basePath: string, repository: string, remote?: string | undefined | null, branch?: string | undefined | null): string
export declare function resolve(uriStr: string, repoBasePath: string): string
export declare function resolveWithOptions(uriStr: string, repoBasePath: string, branch?: string | undefined | null, commit?: string | undefined | null, path?: string | undefined | null): string
export declare function resolveQuery(uriStr: string, repoBasePath: string, path: string): string
export declare function presignRepresentation(uri: string, representation: string, repoBasePath: string, branch?: string | undefined | null, commit?: string | undefined | null, ttlSeconds?: number | undefined | null, httpUrl?: string | undefined | null, bearerToken?: string | undefined | null): Promise<string>
export declare function listRepositories(repoBasePath: string): string
export declare function manifestSchema(): string
export declare function commitSchema(): string
export declare function validateManifest(jsonStr: string): string
export declare function validateCommit(jsonStr: string): string
export declare function mergeMerge(schemaJson: string, base: string, current: string, proposed: string): string
export declare function mergeDiff(schemaJson: string, base: string, candidate: string): string
export declare function storageConfig(): string
/**
 * Ingest raw media bytes into the content-addressed storage engine.
 *
 * This is an async function returning a JavaScript Promise.  The storage
 * backend is determined at runtime by the ``NAP_STORAGE_BACKEND``
 * environment variable.
 *
 * ## Memory Safety (NAPI Buffer Ownership)
 *
 * The incoming [`Buffer`] is **copied** to an owned `Vec<u8>` **before**
 * crossing the await boundary.  Holding a raw pointer to a V8 `ArrayBuffer`
 * across an await point is unsafe because Node's garbage collector may
 * invalidate or relocate the backing store.  By cloning eagerly we avoid
 * use-after-free and data races.
 *
 * # Arguments
 *
 * * `data` — Raw bytes of the media asset (image, audio, mesh, etc.),
 *   passed as a Node.js `Buffer`.
 * * `format` — File extension without a leading dot (e.g. `"png"`,
 *   `"jpg"`, `"wav"`, `"glb"`).
 *
 * # Returns
 *
 * A Promise resolving to the content-addressed hash `sha256:<hex>`.
 */
export declare function ingestMedia(data: Buffer, format: string): Promise<string>
export declare function loreClone(url: string, destPath: string): string
export declare function version(): string
