# Stub for the compiled Rust/PyO3 extension module.
# Source: crates/narrativeengine-py/src/lib.rs

def create_block_json(id: str, content: str) -> str: ...
def generate_candidate_json(lore_json: str, config_json: str) -> str: ...
def render_lore_summary_json(lore_json: str) -> str: ...
def schema_bundle_json() -> str: ...
def version() -> str: ...
