use crate::model::{DocMeta, WorkspaceMeta};
use crate::templates;
use anyhow::Result;
use std::fs;
use std::path::Path;

pub fn compose_readme(
    workspace_root: &Path,
    cargo_meta: &WorkspaceMeta,
    meta: &DocMeta,
) -> Result<String> {
    let template_path = workspace_root.join("README.template.md");
    let content = fs::read_to_string(&template_path)
        .map_err(|e| anyhow::anyhow!("failed to read README.template.md: {e}"))?;

    let variables = build_variables(workspace_root, cargo_meta, meta)?;

    templates::expand_template(&content, workspace_root, &variables)
}

pub fn build_variables(
    workspace_root: &Path,
    cargo_meta: &WorkspaceMeta,
    meta: &DocMeta,
) -> Result<Vec<(String, String)>> {
    let git_remote = std::process::Command::new("git")
        .args(["remote", "get-url", "origin"])
        .current_dir(workspace_root)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_default();

    let generated_warning = format!(
        "> THIS FILE IS GENERATED.\n> DO NOT EDIT.\n> Generated by {} v{}.",
        meta.generator_name, meta.generator_version,
    );

    Ok(vec![
        ("crate_name".to_string(), cargo_meta.name.clone()),
        ("version".to_string(), cargo_meta.version.clone()),
        ("license".to_string(), cargo_meta.license.clone()),
        ("repository".to_string(), git_remote),
        ("generated_warning".to_string(), generated_warning),
    ])
}
