/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function createBlockJson(id: string, content: string): string
export declare function generateCandidateJson(loreJson: string, configJson: string): string
export declare function renderLoreSummaryJson(loreJson: string): string
export declare function schemaBundleJson(): string
export declare function version(): string
export declare class JsNarrativeEngine {
  constructor()
  generateContext(channelId: string, query: string): string
  planContext(totalBlockCount: number): string
  generateContextFromData(inputJson: string): string
  generateBlock(channelId: string, inputQuery: string, parametersJson: string): string
  generateBlocksSequential(channelId: string, previousContext: string, optionsJson: string): string
  generateBlocksParallel(channelId: string, branchContexts: Array<string>, optionsJson: string): string
  setLabConfig(configJson: string): void
  getLabConfig(): string
  static version(): string
}
