import { BaseNarrativeBlock, BaseNarrativeLore } from "./types";

export const MOCK_BLOCKS: BaseNarrativeBlock[] = [
    { id: 1, index: 1, content: "Kael woke up in the cryo-pod with no memory.", happenedAt: 2000, isNotable: true },
    { id: 2, index: 2, content: "The cryo-fluid drained slowly, hissing against the cold floor.", happenedAt: 2050, isNotable: false },
    { id: 3, index: 3, content: "He pushed the heavy glass lid open, shivering violently.", happenedAt: 2100, isNotable: false },
    { id: 4, index: 4, content: "Emergency lights painted the cryo-bay in a dull, pulsing red.", happenedAt: 2150, isNotable: false },
    { id: 5, index: 5, content: "He checked his cybernetic left arm; the servos whined but engaged.", happenedAt: 2200, isNotable: true },
    { id: 6, index: 6, content: "A sharp pain pulsed behind his eyes, a side effect of prolonged stasis.", happenedAt: 2300, isNotable: false },
    { id: 7, index: 7, content: "He stumbled to the nearest wall console to check the ship's status.", happenedAt: 2400, isNotable: false },
    { id: 8, index: 8, content: "The console screen was cracked, displaying a cascade of error logs.", happenedAt: 2450, isNotable: false },
    { id: 9, index: 9, content: "He bypassed the hardware fault using his arm's diagnostic port.", happenedAt: 2600, isNotable: true },
    { id: 10, index: 10, content: "Main power was offline. Auxiliary reserves were at 14%.", happenedAt: 2700, isNotable: false },
    { id: 11, index: 11, content: "Kael found his environmental suit in locker 4A and suited up.", happenedAt: 3000, isNotable: false },
    { id: 12, index: 12, content: "The suit's HUD flickered to life, syncing with his neural link.", happenedAt: 3100, isNotable: false },
    { id: 13, index: 13, content: "He unsealed the cryo-bay doors manually.", happenedAt: 3300, isNotable: false },
    { id: 14, index: 14, content: "The main corridor was devoid of gravity; he pushed off the bulkhead.", happenedAt: 3400, isNotable: false },
    { id: 15, index: 15, content: "Debris floated aimlessly—shattered data pads and frozen coolant droplets.", happenedAt: 3500, isNotable: false },
    { id: 16, index: 16, content: "He navigated through the engineering deck, looking for the AI core.", happenedAt: 3800, isNotable: false },
    { id: 17, index: 17, content: "A localized gravity field caught him off guard near the reactor.", happenedAt: 4000, isNotable: false },
    { id: 18, index: 18, content: "He landed hard, testing the durability of his prosthetic shoulder.", happenedAt: 4050, isNotable: false },
    { id: 19, index: 19, content: "Booting the secondary AI node in engineering took three attempts.", happenedAt: 4300, isNotable: true },
    { id: 20, index: 20, content: "A synthetic voice finally chimed in his earpiece.", happenedAt: 4500, isNotable: false },
    { id: 21, index: 21, content: "'Captain Kael. Diagnostics restored,' ELARA stated flatly.", happenedAt: 4600, isNotable: true },
    { id: 22, index: 22, content: "Kael asked for a ship-wide damage assessment.", happenedAt: 4700, isNotable: false },
    { id: 23, index: 23, content: "ELARA processed the request, the HUD displaying structural schematics.", happenedAt: 4800, isNotable: false },
    { id: 24, index: 24, content: "Several red zones flashed across the mid-section.", happenedAt: 4900, isNotable: false },
    { id: 25, index: 25, content: "The ship's AI, ELARA, reported a hull breach in Sector 4.", happenedAt: 5000, isNotable: false },
    { id: 26, index: 26, content: "Sector 4 housed the primary cargo bay and atmospheric processors.", happenedAt: 5100, isNotable: false },
    { id: 27, index: 27, content: "Kael sprinted down the transit tube toward the breach.", happenedAt: 5300, isNotable: false },
    { id: 28, index: 28, content: "The bulkheads had sealed, trapping the decompression.", happenedAt: 5500, isNotable: false },
    { id: 29, index: 29, content: "He grabbed a heavy plasma welder from a maintenance cache.", happenedAt: 5800, isNotable: true },
    { id: 30, index: 30, content: "Overriding the Sector 4 blast doors required his command codes.", happenedAt: 6000, isNotable: false },
    { id: 31, index: 31, content: "The doors cracked open, and a violent rush of air pushed past him.", happenedAt: 6100, isNotable: false },
    { id: 32, index: 32, content: "He engaged his magnetic boots, locking himself to the deck.", happenedAt: 6200, isNotable: false },
    { id: 33, index: 33, content: "The breach was small, a micro-meteorite puncture, but widening.", happenedAt: 6500, isNotable: false },
    { id: 34, index: 34, content: "Kael applied a durasteel patch and welded the edges shut.", happenedAt: 6800, isNotable: true },
    { id: 35, index: 35, content: "The whistling sound of escaping oxygen finally ceased.", happenedAt: 7000, isNotable: false },
    { id: 36, index: 36, content: "ELARA initiated repressurization of the cargo bay.", happenedAt: 7100, isNotable: false },
    { id: 37, index: 37, content: "With the immediate threat neutralized, Kael inspected the cargo.", happenedAt: 7500, isNotable: false },
    { id: 38, index: 38, content: "Several storage containers had come loose during the impact.", happenedAt: 7600, isNotable: false },
    { id: 39, index: 39, content: "He began securing the magnetic locks on the loose crates.", happenedAt: 7800, isNotable: false },
    { id: 40, index: 40, content: "A strange harmonic vibration caught his attention.", happenedAt: 8000, isNotable: false },
    { id: 41, index: 41, content: "He tracked the hum to a damaged, unmarked stasis pod.", happenedAt: 8100, isNotable: false },
    { id: 42, index: 42, content: "The pod's biometric scanner was dead, the glass frosted over.", happenedAt: 8200, isNotable: false },
    { id: 43, index: 43, content: "Wiping the frost away, he expected to see a crew member.", happenedAt: 8300, isNotable: false },
    { id: 44, index: 44, content: "Instead, the pod was empty save for a single object resting on the floor.", happenedAt: 8400, isNotable: false },
    { id: 45, index: 45, content: "He pried the emergency release lever, popping the pod open.", happenedAt: 8450, isNotable: false },
    { id: 46, index: 46, content: "The ambient temperature dropped sharply as he reached inside.", happenedAt: 8480, isNotable: false },
    { id: 47, index: 47, content: "His cybernetic fingers brushed against cold, unnatural geometry.", happenedAt: 8490, isNotable: false },
    { id: 48, index: 48, content: "Kael found a strange obsidian cube in the cargo bay.", happenedAt: 8500, isNotable: true },
    { id: 49, index: 49, content: "ELARA warns that the cube is emitting a Void signature.", happenedAt: 8600, isNotable: false },
    { id: 50, index: 50, content: "Kael reaches for his rebreather as the alarms scream.", happenedAt: 9000, isNotable: false },
    { id: 51, index: 51, content: "A black mist began venting from the cube's intricate etchings.", happenedAt: 9050, isNotable: true },
    { id: 52, index: 52, content: "The ship's gravity generators flickered and died completely.", happenedAt: 9100, isNotable: false },
    { id: 53, index: 53, content: "Kael dropped the cube, but it remained suspended in the zero-g environment.", happenedAt: 9200, isNotable: false },
    { id: 54, index: 54, content: "Shadows detached from the bulkheads, slithering toward the artifact.", happenedAt: 9300, isNotable: false },
    { id: 55, index: 55, content: "ELARA initiated a localized EMP pulse to disrupt the entity.", happenedAt: 9500, isNotable: true },
    { id: 56, index: 56, content: "The pulse shattered the shadows, sending them recoiling into the vents.", happenedAt: 9600, isNotable: false },
    { id: 57, index: 57, content: "Kael sealed the cube inside a hazardous materials lockbox.", happenedAt: 9800, isNotable: false },
    { id: 58, index: 58, content: "He needed to get the ship to the surface of Kepler-186f immediately.", happenedAt: 10000, isNotable: true },
    { id: 59, index: 59, content: "Returning to the bridge, he strapped into the pilot's chair.", happenedAt: 10200, isNotable: false },
    { id: 60, index: 60, content: "ELARA calculated an aggressive atmospheric entry vector.", happenedAt: 10500, isNotable: false },
    { id: 61, index: 61, content: "The ship shuddered violently as it hit the exosphere.", happenedAt: 10800, isNotable: false },
    { id: 62, index: 62, content: "Plasma licked the viewport screens, glowing a terrifying orange.", happenedAt: 11000, isNotable: false },
    { id: 63, index: 63, content: "Heat shields were holding at 85% capacity.", happenedAt: 11200, isNotable: false },
    { id: 64, index: 64, content: "Kael fought the manual controls to keep the nose aligned.", happenedAt: 11500, isNotable: false },
    { id: 65, index: 65, content: "The toxic green clouds of Kepler-186f swallowed the ship.", happenedAt: 11800, isNotable: true },
    { id: 66, index: 66, content: "Turbulence threw loose items across the bridge.", happenedAt: 12000, isNotable: false },
    { id: 67, index: 67, content: "Altimeter readouts dropped rapidly: 10,000 meters, 8,000 meters.", happenedAt: 12200, isNotable: false },
    { id: 68, index: 68, content: "He fired the retro-thrusters, straining the ship's fatigued chassis.", happenedAt: 12500, isNotable: false },
    { id: 69, index: 69, content: "The ground approached rapidly—a dense jungle of alien flora.", happenedAt: 12800, isNotable: false },
    { id: 70, index: 70, content: "The landing struts deployed with a heavy, mechanical thud.", happenedAt: 13000, isNotable: true },
    { id: 71, index: 71, content: "Impact. The ship settled into the soft, acidic soil of the planet.", happenedAt: 13200, isNotable: true },
    { id: 72, index: 72, content: "Kael let out a breath he didn't realize he was holding.", happenedAt: 13400, isNotable: false },
    { id: 73, index: 73, content: "ELARA ran surface scans; the atmosphere was confirmed lethal.", happenedAt: 13600, isNotable: false },
    { id: 74, index: 74, content: "He checked his suit's oxygen reserves: 12 hours remaining.", happenedAt: 13800, isNotable: false },
    { id: 75, index: 75, content: "He packed a field kit, ensuring his plasma rifle was fully charged.", happenedAt: 14000, isNotable: false },
    { id: 76, index: 76, content: "He secured the lockbox containing the cube to his tactical harness.", happenedAt: 14200, isNotable: false },
    { id: 77, index: 77, content: "The airlock cycled with a hiss, exposing him to the alien world.", happenedAt: 14500, isNotable: true },
    { id: 78, index: 78, content: "Visibility was low, choked by thick, luminescent spores.", happenedAt: 14700, isNotable: false },
    { id: 79, index: 79, content: "He stepped off the ramp, his boots sinking into the violet moss.", happenedAt: 15000, isNotable: false },
    { id: 80, index: 80, content: "The lockbox hummed softly, vibrating against his back.", happenedAt: 15200, isNotable: false },
    { id: 81, index: 81, content: "He activated his wrist-mounted pathfinder module.", happenedAt: 15500, isNotable: false },
    { id: 82, index: 82, content: "A signal beacon was detected three kilometers to the north.", happenedAt: 15800, isNotable: true },
    { id: 83, index: 83, content: "He began the trek, cutting through dense, razor-sharp foliage.", happenedAt: 16000, isNotable: false },
    { id: 84, index: 84, content: "Strange, multi-limbed creatures scurried away from his light.", happenedAt: 16200, isNotable: false },
    { id: 85, index: 85, content: "An acidic rain began to fall, pattering aggressively against his visor.", happenedAt: 16500, isNotable: false },
    { id: 86, index: 86, content: "His suit's corrosive resistant shielding held, but energy drained faster.", happenedAt: 16800, isNotable: false },
    { id: 87, index: 87, content: "The terrain shifted from jungle to a rocky, obsidian plateau.", happenedAt: 17000, isNotable: false },
    { id: 88, index: 88, content: "He noticed the rock formations mirrored the etchings on the cube.", happenedAt: 17200, isNotable: true },
    { id: 89, index: 89, content: "A low rumble vibrated through the ground beneath him.", happenedAt: 17500, isNotable: false },
    { id: 90, index: 90, content: "The beacon signal grew stronger, leading him to a massive crater.", happenedAt: 17800, isNotable: false },
    { id: 91, index: 91, content: "At the center of the crater lay an ancient, derelict structure.", happenedAt: 18000, isNotable: true },
    { id: 92, index: 92, content: "The structure was emitting a harmonic frequency matching the cube's.", happenedAt: 18200, isNotable: false },
    { id: 93, index: 93, content: "Shadows detached from the ruins, swirling in the green mist.", happenedAt: 18500, isNotable: false },
    { id: 94, index: 94, content: "Void-Eaters materialised, blocking his path to the entrance.", happenedAt: 18800, isNotable: true },
    { id: 95, index: 95, content: "Kael leveled his plasma rifle, disabling the safety.", happenedAt: 19000, isNotable: false },
    { id: 96, index: 96, content: "He fired a concentrated blast, incinerating the closest entity.", happenedAt: 19200, isNotable: false },
    { id: 97, index: 97, content: "The lockbox unlatched itself, the cube hovering into the open air.", happenedAt: 19500, isNotable: true },
    { id: 98, index: 98, content: "The cube projected a beam of dark light towards the ruins.", happenedAt: 19700, isNotable: false },
    { id: 99, index: 99, content: "The doors of the ancient structure ground open, revealing an abyss.", happenedAt: 19900, isNotable: true },
    { id: 100, index: 100, content: "Kael took a deep breath of recycled air and stepped inside.", happenedAt: 20000, isNotable: true }
];

export const MOCK_LORE: BaseNarrativeLore[] = [
    { id: "lore-1", content: "The atmosphere on Kepler-186f is toxic without a rebreather.", happenedAt: 1000, isActive: true },
    { id: "lore-2", content: "Captain Kael has a cybernetic left arm from the Sol Wars.", happenedAt: 1005, isActive: true },
    { id: "lore-3", content: "The 'Void-Eaters' are attracted to high-energy signatures.", happenedAt: 1010, isActive: true },
    { id: "lore-4", content: "The USS Daedalus is a deep-space freighter retrofitted for reconnaissance.", happenedAt: 1015, isActive: true },
    { id: "lore-5", content: "ELARA stands for Electronic Logistics and Reconnaissance Automaton.", happenedAt: 1020, isActive: true },
    { id: "lore-6", content: "Obsidian Cubes are Class-Omega artifacts, prohibited by the Terran Coalition.", happenedAt: 1025, isActive: true },
    { id: "lore-7", content: "The Sol Wars ended in 2098 after the destruction of the Lunar colonies.", happenedAt: 1030, isActive: false },
    { id: "lore-8", content: "Kepler-186f's flora secretes a highly acidic neuro-sap.", happenedAt: 1035, isActive: true },
    { id: "lore-9", content: "Cryo-stasis memory fragmentation is a common but temporary condition.", happenedAt: 1040, isActive: true },
    { id: "lore-10", content: "Void signatures disrupt localized gravitational fields and electronics.", happenedAt: 1045, isActive: true },
    { id: "lore-11", content: "Kael's neural link allows him to interface directly with Terran tech.", happenedAt: 1050, isActive: true },
    { id: "lore-12", content: "Sector 4 of the Daedalus houses restricted atmospheric processors.", happenedAt: 1055, isActive: false },
    { id: "lore-13", content: "Standard plasma welders operate at 15,000 degrees Kelvin.", happenedAt: 1060, isActive: true },
    { id: "lore-14", content: "A localized EMP is the only known deterrent for low-tier Void entities.", happenedAt: 1065, isActive: true },
    { id: "lore-15", content: "Terran Hazard Lockboxes are lined with quantum-sealed lead.", happenedAt: 1070, isActive: true },
    { id: "lore-16", content: "The Ruins of Kepler were discovered by probes but never explored by humans.", happenedAt: 1075, isActive: true },
    { id: "lore-17", content: "Magnetic boots are standard issue for zero-gravity EVA and internal breaches.", happenedAt: 1080, isActive: true },
    { id: "lore-18", content: "Dark light projection is a theoretical physics phenomenon linked to the Void.", happenedAt: 1085, isActive: true },
    { id: "lore-19", content: "The Daedalus's heat shields were past their recommended maintenance cycle.", happenedAt: 1090, isActive: false },
    { id: "lore-20", content: "Kael lost his original arm during the Siege of Mare Crisium.", happenedAt: 1095, isActive: true }
];